// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyOCUk14R9JKJsj2ymsorrrzLoJiP8Bz4',
    appId: '1:866681503824:web:ac89968140c41b79e85155',
    messagingSenderId: '866681503824',
    projectId: 'push-notification-b1c43',
    authDomain: 'push-notification-b1c43.firebaseapp.com',
    storageBucket: 'push-notification-b1c43.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU_m081Ri0BXbzwps8MY9sQIUs0F7DAt4',
    appId: '1:866681503824:android:5f111067669b1da5e85155',
    messagingSenderId: '866681503824',
    projectId: 'push-notification-b1c43',
    storageBucket: 'push-notification-b1c43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQCaUPFr1EEetfjDNDgvOAwaRTF56NtEA',
    appId: '1:866681503824:ios:5a1358f356900f27e85155',
    messagingSenderId: '866681503824',
    projectId: 'push-notification-b1c43',
    storageBucket: 'push-notification-b1c43.appspot.com',
    iosBundleId: 'com.example.realtimeChatappAppwrite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQCaUPFr1EEetfjDNDgvOAwaRTF56NtEA',
    appId: '1:866681503824:ios:5a1358f356900f27e85155',
    messagingSenderId: '866681503824',
    projectId: 'push-notification-b1c43',
    storageBucket: 'push-notification-b1c43.appspot.com',
    iosBundleId: 'com.example.realtimeChatappAppwrite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyOCUk14R9JKJsj2ymsorrrzLoJiP8Bz4',
    appId: '1:866681503824:web:01e3eb4fda8a6f77e85155',
    messagingSenderId: '866681503824',
    projectId: 'push-notification-b1c43',
    authDomain: 'push-notification-b1c43.firebaseapp.com',
    storageBucket: 'push-notification-b1c43.appspot.com',
  );
}
